#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/404.html > /dev/null
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://google.com/ permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i "46i error_page 404 /404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
