#!/usr/bin/env bash
# Accepts String as an argument, and pings an IP address 5 times

arg=$1

if [ -z "$arg" ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
        ping -c 5 "$arg"
fi
