#!/usr/bin/env bash
# The script manages the script manage_my_process.
# When passed the argument `start`:
# - Starts manage_my_process
# - Creates a file containings its PID in /var/run/my_process.pid
# - Displays "manage_my_process started"
# When passed the argument `stop`:
# - Stops manage_my_process
# - Deletes the file /var/run/my_process.pid
# - Displays "manage_my_process stopped"
# When passed the argument `restart`:
# - Stops manage_my_process
# - Deletes the file /var/run/my_process.pid
# - Starts manage_my_process
# - Creates a file containing its PID in /var/run/my_process.pid
# - Displays "manage_my_process restarted"
# If any other or no arguments are passed, displays
#+ "Usage: manage_my_process {start|stop|restart}"


# Define the PID file path
PID_FILE="/var/run/my_process.pid"

# Check for the correct number of arguments
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 {start|stop|restart}"
    exit 1
fi

# Function to start the process
start_process() {
        ./manage_my_process &
        echo "$$" > "$PID_FILE"
        echo "manage_my_process started"
}

# Function to stop the process
stop_process() {
        PID=$(cat "$PID_FILE")
        kill "$PID"
        rm "$PID_FILE"
        echo "manage_my_process stopped"
}

# Function to restart the process
restart_process() {
    stop_process
    start_process
    echo "manage_my_process restarted"
}

# Main script logic
case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
