#!/usr/bin/env bash
# Runs the whoami command under the user passed as an argument

if [ $# -gt 1 ];
then
    echo "Usage: 0-iamsomeoneelse <user> (optional)"
    exit 1
fi

if [ $# -eq 0 ] ;
then
    whoami
else
    sudo -u "$1" whoami
fi
